### PR TITLE
Cst criteria and r8 vignette

### LINKED ISSUE #736: Error ('test-ResultFlagsIndependent.R:144:3')
```r
**Describe the bug**

══ Failed tests ════════════════════════════════════════════════════════════════
── Error ('test-ResultFlagsIndependent.R:144:3'): TADA_FindPotentialDuplicates functions do not grow dataset ──
Error in `st_join.sf(near.sites, nhd.catch.all, left = TRUE)`: second argument should be of class sf: maybe revert the first two arguments?
Backtrace:
    ▆
 1. └─EPATADA::TADA_FindPotentialDuplicatesMultipleOrgs(testdat) at test-ResultFlagsIndependent.R:144:3
 2.   └─EPATADA::TADA_FindNearbySites(...) at EPATADA/R/ResultFlagsIndependent.R:1545:5
 3.     ├─dplyr::select(...) at EPATADA/R/GeospatialFunctions.R:3376:3
 4.     ├─dplyr::filter(...) at EPATADA/R/GeospatialFunctions.R:3376:3
 5.     ├─dplyr::mutate(...) at EPATADA/R/GeospatialFunctions.R:3376:3
 6.     ├─dplyr::group_by(...) at EPATADA/R/GeospatialFunctions.R:3376:3
 7.     ├─dplyr::distinct(sf::st_join(near.sites, nhd.catch.all, left = TRUE)) at EPATADA/R/GeospatialFunctions.R:3376:3
 8.     ├─sf::st_join(near.sites, nhd.catch.all, left = TRUE) at EPATADA/R/GeospatialFunctions.R:3376:3
 9.     └─sf:::st_join.sf(near.sites, nhd.catch.all, left = TRUE)

### PR DESCRIPTION
**Pull request by wokenny13**
- Provided additional context and details to sections B, C and D of the R8 vignette (mod 2 and 3 components) and other formatting considerations.
- Incorporated CST magnitude values to an org's criteria table for the case when auto_assign = TRUE. The CST std pollutant names and CST uses are populated as the last two columns. When a CST magnitude value is a string (ex. 'See Table') it will return an NA for the magnitude component. We will also need to consider how to convert magnitude units in the future along with other unique cases that may not translate over correctly between TADA formatting and CST formatting.
-some minor bug fixes in TADA_AssignUsesToAU. 

Ex.
`tada.example <- TADA_DefineCriteriaMethodology(Data_MT_MissoulaCounty, org_id = "MTDEQ", auto_assign = T)`
`tada.example2 <- TADA_DefineCriteriaMethodology(Data_Nutrients_UT, org_id = "UTAHDWQ", auto_assign = T)`
`tada.example <- TADA_DefineCriteriaMethodology(Data_6Tribes_5y_Harmonized, org_id = "MTDEQ", auto_assign = T)`
See section for 'Autoassign criteria table' in the R8 vignette.

### Pull Request Checklist

Preparation

-   [x] Update your branch from the latest `develop` and resolve any merge conflicts

-   [x] Before creating a pull request trigger the [format-update](https://github.com/USEPA/EPATADA/actions/workflows/format-batch-update.yaml) GitHub Action on your branch to format the code

Documentation

-   [x] Add/update inline and/or block comments to clarify complexity, context and intent

-   [x] Add/update function documentation (roxygen), include working examples, build docs locally using devtools::document(), and inspect added/updated help pages for content and format

-   [x] Add/update vignettes for corresponding changes in functionality, list these under articles in _pkgdown.yml, and ensure added/updated vignettes run and build with proper formatting locally

Maintenance & Data Refresh 

-   [x] Add new dependencies to `DESCRIPTION` and document appropriately

-   [x] Run spelling maintenance in `requiredMaintenance.R`

-   [x] If changes affect other package or the shiny app functions, update those impacted functions accordingly

-   [x] If columns were added/updated, add/update them in `RequiredCols.R`

-   [x] Run `.TADA_UpdateRefFiles()` and `.TADA_UpdateExampleData()` locally via `MaintenanceScheduled.R` or trigger the [Component File Update](https://github.com/USEPA/EPATADA/actions/workflows/maintenance-update.yaml) GitHub Action

-   [x] If new example data files were added, document them in `ExampleData.R` and include them in `MaintenanceScheduled.R` for regular refresh

Tests and checks

-   [x] Add/update tests in `tests/testthat` to cover changes

-   [x] Run `devtools::test()` to verify new and existing tests pass

-   [x] Run `devtools::check()` and address any errors, warnings or notes

Pull Request Description

-   [x] Includes a summary of the changes made

-   [x] Includes relevant context/motivation

-   [x] Includes links to related issues or pull requests (keywords like "Closes #issue_number" automatically close related issues when pull request is merged)

Review

-   [x] Review the bot-commented coverage-report generated by [test-coverage](https://github.com/USEPA/EPATADA/blob/develop/.github/workflows/test-coverage.yaml) to confirm all changes are covered by tests

-   [x] Review/accept any bot-suggested format changes
  
-   [x] Request review from at least one developer team member

### CODE REVIEW

**Comment by cristinamullin** [comment]
@wokenny13 FYI I just updated this from develop and Hillary's branch with the bug fix.

File: R/ATTAINSCrosswalks.R [hunk 1]
```diff
@@ -3147,20 +3147,32 @@ TADA_AssignUsesToAU <- function(
 
     # User provides their own AU_UsesRef that has been filled out.
     if (!is.null(AU_UsesRef)) {
+      print(
```
Comment (cristinamullin) [inline R/ATTAINSCrosswalks.R]: Suggest to use **message** instead of **print**. Also, all messages should start with the function name. At some point, I'd like to make this switch consistently across the package - I can add an issue for this.

Suggest to update the language as well for this message: "TADA_AssignUsesToAU: A user supplied crosswalk of Uses and Assessment Units was provided via the AU_UsesRef function input. Prioritizing these matches."

Can you clarify what is means to prioritize these matches? Does that mean no additional uses would be assigned to the assessment units included in the user supplied ref?

File: R/ATTAINSRefTables.R [hunk 2]
```diff
@@ -472,6 +472,306 @@ TADA_AdditionalCharAliasForReview <- function(
 }
 
 
+#' TADA Alias Methodology for ATTAINS and CST Uses Alias Table for Review
+#'
+#' This function first prioritize use name matches between ATTAINS.UseName
+#' and the CST uses application by matching the context2 from ATTAINS UseName
+#' domain with the Human Health and Aquatic Life column indicators in the CST.
+#' Please see the crosswalk done within the function.
```
Comment (cristinamullin) [inline R/ATTAINSRefTables.R]: clarify wording here

File: R/ATTAINSRefTables.R [hunk 3]
```diff
@@ -472,6 +472,306 @@ TADA_AdditionalCharAliasForReview <- function(
...
+#' Users should be aware that a CST magnitude value may get duplicated
+#' for each ATTAINS.UseName. It is up to the user to decide which magnitude
+#' values for a CST use should be appropriately matched to an ATTAINS.UseName.
+#'
+#' Note for Development: We should keep a reference file to indicate
+#' which rows have already been reviewed during this process.In addition,
+#' we can modify the 'strictness' of percent matches. Being more strict
+#' can result in less potential match (false negatives) findings while
+#' less strict may result in greater number of matches that shouldn't
+#' be matched (false positives). Default for now is to be more strict.
```
Comment (cristinamullin) [inline R/ATTAINSRefTables.R:496]: This is a good default

File: R/ATTAINSRefTables.R [hunk 4]
```diff
@@ -472,6 +472,306 @@ TADA_AdditionalCharAliasForReview <- function(
...
+#' @export
+#'
+#' @examples
+#' uses <- TADA_UsesAliasForReview(
+#'   ATTAINS.CST.tolerance = 0.5,
+#'   CST.ATTAINS.tolerance = 0.15  # uses a lower value as CST uses can be very long string.
+#'   )
+#'
+TADA_UsesAliasForReview <- function(
+  includeCST = FALSE,
```
Comment (cristinamullin) [inline R/ATTAINSRefTables.R]: Function input is declared but never used

File: R/ATTAINSRefTables.R [hunk 5]
```diff
@@ -472,6 +472,306 @@ TADA_AdditionalCharAliasForReview <- function(
...
+  displayPercent = FALSE,
+  ATTAINS.CST.tolerance = 1.00,
+  CST.ATTAINS.tolerance = 1.00,
+  ATTAINS.WQX.tolerance = 1.00,
```
Comment (cristinamullin) [inline R/ATTAINSRefTables.R]: ATTAINS.WQX.tolerance and WQX.ATTAINS.tolerance are validated at the start of the function below (checking they are about 1), but they are not used anywhere else in the function. They should either be used or removed to avoid confusion if they should not be edited by the user.

File: R/ATTAINSCrosswalks.R (hunk 1 above)
Comment (wokenny13) [reply R/ATTAINSCrosswalks.R]: Yes this is correct, "no additional uses would be assigned to the assessment units included in the user supplied ref"

File: R/ATTAINSRefTables.R [hunk 6]
```diff
@@ -472,6 +472,306 @@ TADA_AdditionalCharAliasForReview <- function(
...
+  WQX.ATTAINS.tolerance = 1.00
+) {
+  if (
+    ATTAINS.CST.tolerance > 1.00 |
```
Comment (cristinamullin) [inline R/ATTAINSRefTables.R]: Tolerance values are validated only for > 1. They should also be checked for < 0 and NA, so tolerances must be in [0,1].

File: R/ATTAINSRefTables.R [hunk 7]
```diff
@@ -472,6 +472,306 @@ TADA_AdditionalCharAliasForReview <- function(
...
+      CST.ATTAINS.tolerance > 1.00 |
+      ATTAINS.WQX.tolerance > 1.00 |
+      WQX.ATTAINS.tolerance > 1.00
+  ) {
+    stop(
+      "One or more tolerance defined is greater than 1.00. Tolerance cannot exceed 100%."
+    )
+  }
+
+  # Extracts all words from each ATTAINS Parameter Name
```
Comment (wokenny13) [inline R/ATTAINSRefTables.R]: Note to self: change from ATTAINS Parameter Name to ATTAINS Use Name in the comment

File: R/ATTAINSRefTables.R [hunk 8]
```diff
@@ -472,6 +472,306 @@ TADA_AdditionalCharAliasForReview <- function(
...
+      ENTITY_ABBR,
+      ENTITY_NAME,
+      CRITERIATYPEAQUAHUMHLTH,
+      CRITERIATYPEFRESHSALTWATER,
+      CRITERIATYPE_ACUTECHRONIC,
+      USE_CLASS_NAME_LOCATION_ETC
+    ) |>
+    dplyr::distinct()
+
+  # Extracts all words from each CST Pollutant Name
```
Comment (wokenny13) [inline R/ATTAINSRefTables.R]: Change comment from "Pollutant Name" to "CST Use"

File: R/ATTAINSRefTables.R [hunk 9]
```diff
@@ -472,6 +472,306 @@ TADA_AdditionalCharAliasForReview <- function(
...
+      )
+    ) |>
+    tidyr::unnest(cols = c(name_words)) |>
+    dplyr::filter(
+      !name_words %in% c(" ", "-", "%", "--", "&", "#", "and", "or")
+    ) |>
+    dplyr::distinct(USE_CLASS_NAME_LOCATION_ETC, name_words, .keep_all = TRUE)
+
+  # uppercase for consistency
+  CST2$name_words <- toupper(gsub("[^[:alnum:] ]", "", CST2$name_words))
```
Comment (cristinamullin) [inline R/ATTAINSRefTables.R]: After gsub("[^[:alnum:] ]", "", ...), some tokens can become "", and these aren’t removed. Filter out empty strings to avoid spurious matches.

Suggestions: 

Replace the ATTAINSUseRef2 section
```r
ATTAINSUseRef2 <- ATTAINSUseRef |>
  dplyr::mutate(name_words = stringr::str_split(name, pattern = " ")) |>
  tidyr::unnest(cols = c(name_words)) |>
  dplyr::filter(
    !name_words %in% c(" ", "-", "%", "--", "&", "#", "and", "or")
  ) |>
  dplyr::mutate(
    name_words = toupper(gsub("[^[:alnum:] ]", "", name_words))
  ) |>
  dplyr::filter(name_words != "") |>
  dplyr::distinct(name, name_words, .keep_all = TRUE)
```

Replace the CST2 section:
```r
CST2 <- CST |>
  dplyr::mutate(
    name_words = stringr::str_split(USE_CLASS_NAME_LOCATION_ETC, pattern = " ")
  ) |>
  tidyr::unnest(cols = c(name_words)) |>
  dplyr::filter(
    !name_words %in% c(" ", "-", "%", "--", "&", "#", "and", "or")
  ) |>
  dplyr::mutate(
    name_words = toupper(gsub("[^[:alnum:] ]", "", name_words))
  ) |>
  dplyr::filter(name_words != "") |>
  dplyr::distinct(USE_CLASS_NAME_LOCATION_ETC, name_words, .keep_all = TRUE)
```

File: R/ATTAINSCrosswalks.R (hunk 1 above)
Comment (cristinamullin) [reply R/ATTAINSCrosswalks.R]: Thanks for clarifying - let's include that in the message too:

"TADA_AssignUsesToAU: When AU_UsesRef (a user-provided mapping of Assessment Units to Uses) is supplied, the function assigns only the Uses listed in that mapping to the AUs it contains and does not append any additional Uses"

File: R/ATTAINSRefTables.R [hunk 10]
```diff
@@ -472,6 +472,306 @@ TADA_AdditionalCharAliasForReview <- function(
...
+    ATTAINSUseRef,
+    by = c("ATTAINS.OrganizationIdentifier", "CRITERIATYPEAQUAHUMHLTH"),
+    relationship = "many-to-many"
+  )
+
+  # Look for percent word matches between ATTAINS and CST as additional matches
+  temp_ATTAINS_CST2 <- dplyr::right_join(
+    CST2,
+    ATTAINSUseRef2,
+    by = c("name_words"),
```
Comment (cristinamullin) [inline R/ATTAINSRefTables.R]: Should the join include "ATTAINS.OrganizationIdentifier"?

File: R/ATTAINSRefTables.R [hunk 11]
```diff
@@ -472,6 +472,306 @@ TADA_AdditionalCharAliasForReview <- function(
...
+  rm(ATTAINS.raw)
+
+  # pulls in CST and extract relevant columns
+  CriteriaSearchToolRef <- system.file(
+    "extdata",
+    "CriteriaSearchToolRef.rda",
+    package = "EPATADA"
+  )
+
+  load(CriteriaSearchToolRef)
```
Comment (cristinamullin) [inline R/ATTAINSRefTables.R]: Using load(CriteriaSearchToolRef) creates the object CriteriaSearchToolRef in the function environment, then you access it directly and later reuse it. Better to capture the object name returned by load() to keep code explicit.

For example, see TADA_FlagFraction:
```r
# read in fraction reference table from extdata and filter
  file_path <- system.file("extdata", "WQXcharValRef.rda", package = "EPATADA")
  load(file_path)
  rm(file_path)
  frac.ref <- dplyr::filter(WQXcharValRef, Type == "CharacteristicFraction")
  rm(WQXcharValRef)
```

File: R/CriteriaMethods.R [hunk 12]
```diff
@@ -620,6 +630,136 @@ TADA_DefineCriteriaMethodology <- function(
...
+              !is.na(ATTAINS.OrganizationIdentifier),
+              ATTAINS.OrganizationIdentifier %in%
+                unique(DefineCriteriaMethodology$ATTAINS.OrganizationIdentifier)
+            )
+          CriteriaSearchToolRef <- system.file(
+            "extdata",
+            "CriteriaSearchToolRef.rda",
+            package = "EPATADA"
+          )
+          load(CriteriaSearchToolRef)
```
Comment (cristinamullin) [inline R/CriteriaMethods.R]: see comment above

File: R/CriteriaMethods.R [hunk 13]
```diff
@@ -620,6 +630,136 @@ TADA_DefineCriteriaMethodology <- function(
...
+          CriteriaSearchToolRef <- CriteriaSearchToolRef |>
+            dplyr::mutate(dplyr::across(where(is.character), toupper))
+          DefineCriteriaMethodology <- DefineCriteriaMethodology |>
+            dplyr::mutate(dplyr::across(where(is.character), toupper))
+          DefineCriteriaMethodology2 <- DefineCriteriaMethodology |>
+            dplyr::left_join(
+              CST_ATTAINS_Param,
+              by = "ATTAINS.ParameterName",
+              relationship = "many-to-many"
```
Comment (cristinamullin) [inline R/CriteriaMethods.R:686]: The relationship = "many-to-many" requires dplyr >= 1.1.0. Let's add that to the description file:
```r
dplyr (>= 1.1.0)
```

File: inst/WORDLIST [hunk 14]
```diff
@@ -54,6 +57,7 @@ CharacteristicNames
 CharacteristicsForDepthProfile
 Chilton
 Coli
+CommunityHub
```
Comment (cristinamullin) [inline inst/WORDLIST]: Should this be TADACommunityHub for consistency?

File: R/ATTAINSRefTables.R (hunk 4 above)
Comment (wokenny13) [reply R/ATTAINSRefTables.R]: This function is meant for the CST and ATTAINS use alias. removing this arg input.

File: R/ATTAINSRefTables.R (hunk 5 above)
Comment (wokenny13) [reply R/ATTAINSRefTables.R]: not needed in this function. Was used for AdditionalParameterAliasForReview function

File: R/ATTAINSRefTables.R (hunk 10 above)
Comment (wokenny13) [reply R/ATTAINSRefTables.R]: I cleaned up the function a bit and identified some messy joins and bugs. The function should now run significantly faster and should be joined correctly here now.

**Comment by wokenny13** [comment]
@hillarymarler @cristinamullin The R8 demo vignette should now reflect the use of TADA_FindPotentialDuplicatesMultipleOrgs() again and is working as expected when you run TADA_ViewATTAINS! Please let me know if you have the time to review the edits made and make any updates as needed to the vignette.

The function for TADA_UsesAliasForReview has also been updated and cleaned. It should now run much quicker and efficiently. Additional edits will likely need to be considered for leveraging this auto_assign CST magnitude values to TADA_DefineCriteriaMethods(auto_assign = TRUE), but can be used as a placeholder for the time being as we do additional testing in the future.

**Review by cristinamullin — APPROVED** [review]
