### PR TITLE
799 need to ensure that the cst units matches and is converted to the tadaresultmeasuremeasureunitcode when autoassign t in tada definecriteriamethodology

### LINKED ISSUE #799: Need to ensure that the CST units matches and is converted to the TADA.ResultMeasure.MeasureUnitCode when autoassign = T in TADA_DefineCriteriaMethodology()
**Describe the bug**

We need to ensure the MagnitudeUnits from a TADA compatible criteria table matches the units found in a TADA data.frame. 

With auto_assign methods, we may pull in the CST units which may not match the TADA.ResultMeasure.MeasureUnitCode. Likewise we need to ensure any magnitudeUnits currently in the TADACommunityHub are coming from TADA.ResultMeasure.MeasureUnitCode domain. See comment related to this in https://github.com/USEPA/TADAShinyAnalyze/pull/22

Example: 
MagnitudeUnit for E.coli if it is shown as #/100mL in the TADA-criteria table cannot be analyzed as it does not match the TADA data frame's CFU/100ML units in the TADAShinyAnalyze app. This will become an error in the TADA package side as well downstream when we continue making progress in analysis development.

### LINKED ISSUE #863: Create WQXCharUnitRef as a internal file in inst/extdata

### PR DESCRIPTION
**Pull request by wokenny13**
There are still additional units from the CST units that would need to be converted. I converted those found as priority char units for now from the CST and added on a few rows to that table (is this an appropriate space to include those unit conversion?). 

See CST_Units3_NA below for those that are still unmatched.
```{r}
# pulls in CriteriaSearchToolRef.rda
file_path <- system.file(
  "extdata",
  "CriteriaSearchToolRef.rda",
  package = "EPATADA"
)
load(file_path)
# remove intermediate variable
rm(file_path)

# convert greek letter in ug/l
CriteriaSearchToolRef$UNIT_NAME <- str_replace_all(CriteriaSearchToolRef$UNIT_NAME, "\u00B5", "u")

# select the units and parameter it's associated with
CST_Units <- CriteriaSearchToolRef |> 
  dplyr::select(STD_POLLUTANT_NAME, UNIT_NAME) |> 
  dplyr::mutate(across(where(is.character), str_to_upper)) |>
  dplyr::distinct()

# WQX or TADA Priority Unit Ref
WQXunitRef <- read.csv("C:/Users/kwong01/EPATADA/inst/extdata/WQXunitRef.csv") |>
  dplyr::mutate(across(where(is.character), str_to_upper))

TADAPriorityCharConvertRef <- read_csv("inst/extdata/TADAPriorityCharConvertRef.csv") |>
  dplyr::mutate(across(where(is.character), str_to_upper))

# join table with TADA Unit Ref
CST_Units3 <- CST_Units |>
  dplyr::left_join(TADAPriorityCharConvertRef, by = c("UNIT_NAME" = "Code")) |>
  dplyr::distinct()

# identify units that still needs to be converted
CST_Unit3_NA <- CST_Units3 |>
  dplyr::filter(dplyr::if_any(Conversion.Factor, is.na))
```

### Pull Request Checklist

Preparation

-   [x] Update your branch from the latest `develop` and resolve any merge conflicts

-   [ ] Before creating a pull request trigger the [format-update](https://github.com/USEPA/EPATADA/actions/workflows/format-batch-update.yaml) GitHub Action on your branch to format the code

Documentation

-   [x] Add/update inline and/or block comments to clarify complexity, context and intent

-   [x] Add/update function documentation (roxygen), include working examples, build docs locally using devtools::document(), and inspect added/updated help pages for content and format

-   [x] Add/update vignettes for corresponding changes in functionality, list these under articles in _pkgdown.yml, and ensure added/updated vignettes run and build with proper formatting locally

Maintenance & Data Refresh 

-   [x] Add new dependencies to `DESCRIPTION` and document appropriately

-   [x] Run spelling maintenance in `requiredMaintenance.R`

-   [x] If changes affect other package or the shiny app functions, update those impacted functions accordingly

-   [x] If columns were added/updated, add/update them in `RequiredCols.R`

-   [ ] Run `.TADA_UpdateRefFiles()` and `.TADA_UpdateExampleData()` locally via `MaintenanceScheduled.R` or trigger the [Component File Update](https://github.com/USEPA/EPATADA/actions/workflows/maintenance-update.yaml) GitHub Action

-   [x] If new example data files were added, document them in `ExampleData.R` and include them in `MaintenanceScheduled.R` for regular refresh

Tests and checks

-   [x] Add/update tests in `tests/testthat` to cover changes

-   [ ] Run `devtools::test()` to verify new and existing tests pass

-   [ ] Run `devtools::check()` and address any errors, warnings or notes

Pull Request Description

-   [x] Includes a summary of the changes made

-   [x] Includes relevant context/motivation

-   [x] Includes links to related issues or pull requests (keywords like "Closes #issue_number" automatically close related issues when pull request is merged)

Review

-   [ ] Review the bot-commented coverage-report generated by [test-coverage](https://github.com/USEPA/EPATADA/blob/develop/.github/workflows/test-coverage.yaml) to confirm all changes are covered by tests

-   [x] Review/accept any bot-suggested format changes
  
-   [x] Request review from at least one developer team member

### CODE REVIEW

**Comment by cristinamullin** [comment]
Running into this intermittent check failure related to the examples in TADA_DefineCriteriaMethodology. Can we address this as part of this PR?

```r
❯ checking examples ... [36s/109s] ERROR
  Running examples in ‘EPATADA-Ex.R’ failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: TADA_DefineCriteriaMethodology
  > ### Title: Criteria and Methodology Template
  > ### Aliases: TADA_DefineCriteriaMethodology
  > 
  > ### ** Examples
  > 
  > # Example 1
  > # First, generate and fill out a parameter crosswalk (see TADA_ParametersForAnalysis()):
  > paramRef_UT <- TADA_ParametersForAnalysis(Data_Nutrients_UT, org_id = "UTAHDWQ", excel = FALSE)
  > paramRef_UT2 <- dplyr::mutate(paramRef_UT, ATTAINS.ParameterName = dplyr::case_when(
  +   grepl("AMMONIA", TADA.ComparableDataIdentifier) ~ "AMMONIA, TOTAL",
  +   grepl("NITRATE", TADA.ComparableDataIdentifier) ~ "NITRATE",
  +   grepl("NITROGEN", TADA.ComparableDataIdentifier) ~ "NITRATE/NITRITE (NITRITE + NITRATE AS N)"
  + ))
  > paramRef_UT3 <- TADA_ParametersForAnalysis(
  +   Data_Nutrients_UT,
  +   paramRef = paramRef_UT2, org_id = "UTAHDWQ", excel = FALSE
  + )
  > 
  > # Next, enter the crosswalk generated above as the paramRef function input
  > # for TADA_UsesForAnalysis():
  > usesRef_UT <- TADA_UsesForAnalysis(
  +   Data_Nutrients_UT,
Error: Error: R CMD check found ERRORs
Execution halted
  +   paramRef = paramRef_UT3, org_id = c("UTAHDWQ"), excel = FALSE
  + )
  > 
  > # Now, run TADA_MLSummary()
  > MLSummaryRef_UT <- TADA_MLSummary(
  +   Data_Nutrients_UT,
  +   org_id = c("UTAHDWQ"),
  +   AU_UsesRef = NULL, AUMLRef = NULL,
  +   usesRef = usesRef_UT,
  +   excel = FALSE
  + )
  [1] "displayNA = FALSE: This MLSummaryRef table will only display parameters and uses for a ML if it contains data collected for that TADA.CharacteristicName in your TADA data frame."
  > 
  > DefineCriteriaMethodology_UT <- TADA_DefineCriteriaMethodology(
  +   Data_Nutrients_UT,
  +   MLSummaryRef = MLSummaryRef_UT,
  +   displayUniqueId = TRUE,
  +   excel = FALSE
  + )
  > 
  > # Example 2: fill template with EPA304(a) criteria
  > epa_only <- TADA_DefineCriteriaMethodology(
  +   Data_MT_MissoulaCounty,
  +   org_id = "USEPA",
  +   auto_assign = TRUE
  + )
  [1] "TADA_DefineCriteriaMethodology: auto_assign = TRUE was selected. Running TADA_ParametersForAnalysis with default assignment."
  [1] "TADA_ParametersForAnalysis: auto_assign == 'Org' was selected, finding an exact ATTAINS.ParameterName match, by ATTAINS.OrganizationName, for each TADA.ComparableDataIdentifier - by WQP CharacteristicName if one is found."
  [1] "TADA_DefineCriteriaMethodology: auto_assign = TRUE was selected. Running TADA_UsesForAnalysis with default assignment."
  [1] "TADA_UsesForAnalysis: auto_assign == TRUE was selected, assigning all unique ATTAINS.UseName, by ATTAINS.OrganizationIdentifier, to any ATTAINS.ParameterName that an organization have not done assessments for in prior ATTAINS cycle. Please review carefully and Exclude rows as needed."
  [1] "TADA_DefineCriteriaMethodology: auto_assign = TRUE was selected. Running TADA_MLSummary with default assignment."
  [1] "TADA_MLSummary: displayNA = TRUE: This MLSummaryRef table will display ALL parameters and uses for a ML/AU regardless if it contains data collected for that TADA.CharacteristicName in your TADA data frame."
  [1] "TADA_DefineCriteriaMethodology: displayUniqueId == FALSE was selected, TADA.ComparableDataIdentifier is converted to NA and duplicated rows are removed. Users are recommended to fill out any applicable combinations of Characteristic, Fraction and Speciation for analysis."
  [1] "TADA_DefineCriteriaMethodology: USEPA was included in your 'org_id': Including EPA304a recommended criteria by each unique TADA.CharacteristicName if one is found."
  > 
  > # Example 3: fill template with EPA304(a)
  > # and ATTAINS parameters and uses for MTDEQ:
  > epa_MT <- TADA_DefineCriteriaMethodology(Data_MT_MissoulaCounty,
  +   org_id = c("USEPA", "MTDEQ"), auto_assign = TRUE
  + )
  [1] "TADA_DefineCriteriaMethodology: auto_assign = TRUE was selected. Running TADA_ParametersForAnalysis with default assignment."
  [1] "TADA_ParametersForAnalysis: More than one org_name was defined in your dataframe. Generating duplicate rows of TADA.ComparableDataIdentifier for each org."
  [1] "TADA_ParametersForAnalysis: auto_assign == 'Org' was selected, finding an exact ATTAINS.ParameterName match, by ATTAINS.OrganizationName, for each TADA.ComparableDataIdentifier - by WQP CharacteristicName if one is found."
  [1] "TADA_DefineCriteriaMethodology: auto_assign = TRUE was selected. Running TADA_UsesForAnalysis with default assignment."
  [1] "TADA_UsesForAnalysis: auto_assign == TRUE was selected, assigning all unique ATTAINS.UseName, by ATTAINS.OrganizationIdentifier, to any ATTAINS.ParameterName that an organization have not done assessments for in prior ATTAINS cycle. Please review carefully and Exclude rows as needed."
  [1] "TADA_DefineCriteriaMethodology: auto_assign = TRUE was selected. Running TADA_MLSummary with default assignment."
  [1] "TADA_MLSummary: displayNA = TRUE: This MLSummaryRef table will display ALL parameters and uses for a ML/AU regardless if it contains data collected for that TADA.CharacteristicName in your TADA data frame."
  [1] "EQ_DomainValues: For param_name the values in the 'name' column of the function output are the allowable values for rExpert Query functions."
  EQ_DomainValues: domain list retrieved from ATTAINS web services.
  TADA_DefineCriteriaMethodology: auto_assign = TRUE was selected.
  Finding an alias match between ATTAINS parameter name and Criteria Search Tool (CST) standardized pollutant names.
  Finding an alias match between ATTAINS use name and Criteria Search Tool (CST) uses.
  If an ATTAINS.ParameterName and ATTAINS.UseName alias was found, populating these rows with the CST magnitude values.
  A many-to-many match is likely. User review is needed to ensure the proper parameter and uses from ATTAINS and CST alias crosswalk was accomplished (remove or add rows as needed).
  Warning in open.connection(con, "rb") :
    URL 'https://attains.epa.gov/attains-public/api/domains?domainName=UseName': Timeout of 60 seconds was reached
  Warning in readChar(con, 5L, useBytes = TRUE) :
    cannot open compressed file 'inst/extdata/DomainValues.rda', probable reason 'No such file or directory'
  Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
  Calls: TADA_DefineCriteriaMethodology ... TADA_UsesAliasForReview -> <Anonymous> -> <Anonymous> -> load -> readChar
```

**Comment by wokenny13** [comment]
> ```r
> Warning in open.connection(con, "rb") :
>     URL 'https://attains.epa.gov/attains-public/api/domains?domainName=UseName': Timeout of 60 seconds was reached
>   Warning in readChar(con, 5L, useBytes = TRUE) :
>     cannot open compressed file 'inst/extdata/DomainValues.rda', probable reason 'No such file or directory'
>   Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection
> ```

**Warning in open.connection(con, "rb") :
    URL 'https://attains.epa.gov/attains-public/api/domains?domainName=UseName': Timeout of 60 seconds was reached
  Warning in readChar(con, 5L, useBytes = TRUE) :
    cannot open compressed file 'inst/extdata/DomainValues.rda', probable reason 'No such file or directory'
  Error in readChar(con, 5L, useBytes = TRUE) : cannot open the connection**

@hillarymarler I think this is occurring when the function calls on rExpertQuery, do you have suggestions on how to pull in the DomainValues.rda in the r documentation examples? Or if r documentation examples should be calling on rExpertQuery?

**Comment by wokenny13** [comment]
@cristinamullin This is ready for review. If additional check fails occur, I will take a look to address them. Some checklist items to review:

Note: did not accept all air formatting so this check will not pass. See stop_words vector list in ATTAINSRefTables.R for reference. If there is preference to accept air formatting for this, I am fine with doing so.

1) TADA_GetTADACharAliasRef() and TADA_UpdateTADACharAliasRef() - returns the ATTAINS, WQX, and CST Char Alias Ref table which contains the source from WQXCharRef as well as additional rows using the TADA methodology. TADA team can review this csv file and select "APPROVED" or "REJECTED" in the review column and update the Last.Change.Date. Any rows that gets reviewed will not be removed if you run TADA_UpdateTADACharAliasRef(). Currently, default tolerance is what I used as a placeholder.

Feel free to play around with the tolerance modification in this function.

2) TADA_GetTADAUsesAliasRef() and TADA_UpdateTADAUsesAliasRef() - returns the ATTAINS uses to CST uses crosswalk using TADA methodology. TADA team can review this csv file and select "APPROVED" or "REJECTED" in the review column and update the Last.Change.Date.

3) For the fix for handling mismatching units from the CST MagnitudeUnits and a user's TADA data frame. This is being handled by adding additional rows in the TADAPriorityCharConvertRef. Is this a good spot to handle these? The fix for this is being included directly in the TADA_DefineCriteriaMethodology() function where auto_assign = TRUE. There is also an error handling message for when these instances occur. See example code and output:
`R5_IL <- TADA_DefineCriteriaMethodology(Data_R5_TADAPackageDemo, org_id = "IL_EPA", auto_assign = T) `
image

4) Now, applying these changes from 1 to 3 above, we can test out the updated CharAliasRef and UsesAliasRef which will be leveraged in TADA_DefineCriteriaMethodology() when auto_assign = T. You can look through the autoassign method for any other ATTAINS org_ids as desired. Also, look at the additional CST columns that is now included in this output.

Example codes to run and test:
```{r}
param_xwalk <- TADA_GetTADACharAliasRef(set.all.tolerance = 0.9)
uses_xwalk_low_tolerance <- TADA_GetTADAUsesAliasRef(set.all.tolerance = 0.10)
uses_xwalk_high_tolerance <- TADA_GetTADAUsesAliasRef(set.all.tolerance = 1.00)

Criteria_Data_6Tribes_5y_Harmonized <- TADA_DefineCriteriaMethodology(Data_6Tribes_5y_Harmonized, org_id = "MEDEP", auto_assign = T)
MT_ph_coli <- TADA_DefineCriteriaMethodology(Data_MT_MissoulaCounty, org_id = "MTDEQ", auto_assign = T)
Utah_Nutrients_criteria <- TADA_DefineCriteriaMethodology(Data_Nutrients_UT, org_id = "UTAHDWQ", auto_assign = T)
```

File: dev/Draft/Draft_TADA_autoassign_duration.R
Comment (cristinamullin) [inline dev/Draft/Draft_TADA_autoassign_duration.R:1]: Should this draft file be included?

File: R/ATTAINSRefTables.R [hunk 1]
```diff
@@ -1,140 +1,20 @@
-# Used to store cached ATTAINSParamToWQPCharRef Reference Table
-ATTAINSParamToWQPCharRef_Cached <- NULL
+# Used to store cached TADACharAliasRef Reference Table
+TADACharAliasRef_Cached <- NULL
 
-#' ATTAINS Parameter and WQP Characteristic Alias Reference Table
+#' ATTAINS Parameter, CST Pollutant and WQP Characteristic Alias Reference Table
```
Comment (cristinamullin) [inline R/ATTAINSRefTables.R]: Suggest to move these parameter and uses crosswalk functions to TADARefTables.R or a new .R file

File: R/ATTAINSRefTables.R [hunk 2]
```diff
@@ -1,140 +1,20 @@
...
 #'
-#' Function downloads and returns the newest available crosswalk of alias
-#' matches between ATTAINS.ParameterName and TADA.CharacteristicName.
+#' Function downloads and returns the newest available crosswalk of alias matches
+#' between ATTAINS.ParameterName, CST.PollutantName and TADA.CharacteristicName
```
Comment (cristinamullin) [inline R/ATTAINSRefTables.R]: The HarmonizationTemplate.csv includes synonyms across characteristic, fraction, and speciation combinations in WQX/WQP. I am wondering if it could make sense to combine that with this synonym table? Let's discuss.

File: R/MaintenanceScheduled.R [hunk 3]
```diff
@@ -62,6 +62,7 @@
       .TADA_UpdateMeasureQualifierCodeRef()
       .TADA_UpdateMonLocTypeRef()
       .TADA_UpdateWQPOrganizationRef()
+      .TADA_UpdateWQXCharAliasRef()
```
Comment (cristinamullin) [inline R/MaintenanceScheduled.R:65]: Should TADA_UpdateTADACharAliasRef() be included here as well? Since that is internal, let's update the function to include a period at the start to match the others. 

.TADA_UpdateTADACharAliasRef()

File: inst/extdata/TADACharAliasRef.csv
Comment (cristinamullin) [inline inst/extdata/TADACharAliasRef.csv:1]: If we edit this manually, will the function retain the manual edits made after the file is updated via TADA_UpdateTADACharAliasRef()?

Comment (wokenny13) [reply inst/extdata/TADACharAliasRef.csv]: Yes (at least it should be). It would be good to double check to ensure this is actually happening. Any manual edits to those sourced as TADA.AliasMatch that has its review column as (APPROVED/REJECTED) should be kept in the table when you run TADA_UpdateTADACharAliasRef().

If there may be cases where we would want to keep any REJECTED values from WQX this could be done too, though I am unsure if we want to reject any values from the WQX source - as I would assume they should be already reviewed and good to go.

File: R/WQPWQXRefTables.R [hunk 4]
```diff
@@ -1535,3 +1563,162 @@ TADA_GetMeasureQualifierCodeRef <- function(
...
+#'   attempts to download the latest Characteristic Alias reference table directly from WQX,
+#'   returning it without updating the cache. Errors if the download fails. If FALSE
+#'   (default), uses a cached copy when available and updates the cache; on download
+#'   failure, falls back to the package’s internal file.
+#' @param refresh Logical. Only used when download_only = FALSE. If TRUE, ignore any
+#'   cached copy and attempt to retrieve a fresh table (download, falling back to the
+#'   package’s internal file on failure), then update the cache. If FALSE (default),
+#'   return the cached table when available. Ignored when download_only = TRUE.
+#' @export
+TADA_GetWQXCharAliasRef <- function(download_only = FALSE, refresh = FALSE) {
```
Comment (cristinamullin) [inline R/WQPWQXRefTables.R:1580]: This new TADA_GetWQXCharAliasRef() function should be leveraged in any other functions in the package where you need to bring in the WQX char alias table. You can use the function instead of reading the file WQXCharAliasRef.rda from extdata. 

Same situation for TADAUsesAliasRef.csv and TADACharAliasRef.csv. You can use the new get functions with download = FALSE, to get the internal copy instead of reading the extdata .csv or .rda files directly in other functions.

**Comment by wokenny13** [comment]
@cristinamullin  This should be ready for review. I want to think a bit more about editing of the TADAUsesAliasRef table output which I think would be better for a separate PR once this one has been merged.

See example below on how someone might edit the TADACharAliasRef table:

A 3-way crosswalk between 2,4,5-T, 2,4,5-TP, and 2-4,5-T between WQX, ATTAINS and CST occur. TADA recommendation is for approval as the WQX and CST CAS matched. However, it seems like the ATTAINS ParameterName match with 2,4,5-TP may not be synonmous. As pairwise 'duplicates' were removed this will only be shown as one row. We can label this row as 'rejected' and add another row manually to the table and label it as approved without the ATTAINS.ParameterName populated in this scenario. Updating the table should not remove these rows that have been reviewed.

image

**Comment by cristinamullin** [comment]
> @cristinamullin This should be ready for review. I want to think a bit more about editing of the TADAUsesAliasRef table output which I think would be better for a separate PR once this one has been merged.
> 
> See example below on how someone might edit the TADACharAliasRef table:
> 
> A 3-way crosswalk between 2,4,5-T, 2,4,5-TP, and 2-4,5-T between WQX, ATTAINS and CST occur. TADA recommendation is for approval as the WQX and CST CAS matched. However, it seems like the ATTAINS ParameterName match with 2,4,5-TP may not be synonmous. As pairwise 'duplicates' were removed this will only be shown as one row. We can label this row as 'rejected' and add another row manually to the table and label it as approved without the ATTAINS.ParameterName populated in this scenario. Updating the table should not remove these rows that have been reviewed.
> 
> image

Thanks for sharing an example. This makes sense to me.

**Review by cristinamullin — APPROVED** [review]
