### PR TITLE
Module 3 tada create param ref and tada create use param ref updates

### LINKED ISSUE #608: Intermittent check issues
**Describe the bug**

```r
❯ checking examples ... [138s] ERROR
  Running examples in 'EPATADA-Ex.R' failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: TADA_FindNearbySites
  > ### Title: Identify and group nearby monitoring locations (UNDER ACTIVE
  > ###   DEVELOPMENT)
  > ### Aliases: TADA_FindNearbySites
  > 
  > ### ** Examples
  > 
  > GroupNearbySites_100m <- TADA_FindNearbySites(Data_Nutrients_UT)
  Transforming your data into a spatial object.
  No NHD HR features associated with your WQP observations.
  Error in `vec_rbind()`:
  ! `c()` method returned a vector of unexpected size 97 instead of 95.
  ℹ In file 'c.c' at line 412.
  ℹ This is an internal error that was detected in the vctrs package.
    Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex (<https://tidyverse.org/help/>) and the full backtrace.
  Backtrace:
      ▆
   1. ├─EPATADA::TADA_FindNearbySites(Data_Nutrients_UT)
   2. │ └─dplyr::bind_rows(nhd.catch) at EPATADA/R/Utilities.R:676:3
   3. │   └─vctrs::vec_rbind(!!!dots, .names_to = .id, .error_call = current_env())
   4. └─rlang:::stop_internal_c_lib(...)
   5.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)
  Execution halted
  Examples with CPU (user + system) or elapsed time > 5s
                             user system elapsed
  TADA_AggregateMeasurements 9.71   0.72   10.43

❯ checking Rd line widths ... NOTE
  Rd file 'TADA_AutoClean.Rd':
    \examples lines wider than 100 characters:
       # https://www.waterqualitydata.us/#statecode=US%3A09&characteristicType=Nutrient&startDateLo=04-01-[202](https://github.com/USEPA/EPATADA/actions/runs/15682804460/job/44178236676#step:6:204)3&startDateHi=11-01-2023&mimeType ... [TRUNCATED]
       stationProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Station/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
       physchemProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Result/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
       projectProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Project/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
  
  Rd file 'TADA_CheckRequiredFields.Rd':
    \examples lines wider than 100 characters:
       # Example WQP URL: https://www.waterqualitydata.us/#statecode=US%3A09&characteristicType=Nutrient&startDateLo=04-01-2023&startDateHi=11 ... [TRUNCATED]
       stationProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Station/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
       physchemProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Result/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
       projectProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Project/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
  
  Rd file 'TADA_CreateDateTime.Rd':
    \examples lines wider than 100 characters:
       # Example WQP URL: https://www.waterqualitydata.us/#statecode=US%3A09&characteristicType=Nutrient&startDateLo=04-01-2023&startDateHi=11 ... [TRUNCATED]
       stationProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Station/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
       physchemProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Result/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
       projectProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Project/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
  
  Rd file 'TADA_OrderCols.Rd':
    \examples lines wider than 100 characters:
       # Example WQP URL: https://www.waterqualitydata.us/#statecode=US%3A09&characteristicType=Nutrient&startDateLo=04-01-2023&startDateHi=11 ... [TRUNCATED]
       stationProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Station/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
       physchemProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Result/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
       projectProfile <- TADA_ReadWQPWebServices("https://www.waterqualitydata.us/data/Project/search?statecode=US%3A09&characteristicType=Nut ... [TRUNCATED]
  
  These lines will be truncated in the PDF manual.
```

### PR DESCRIPTION
**Pull request by wokenny13**
This PR focuses on the updates that have been made to TADA_CreateParamRef and TADA_CreateUseParamRef

(Next pull request will focus on the additional Spatial crosswalks and TADA_DefineCriteriaMethodology functions. Excluded those functions from this PR.)

In this PR please look through:

- TADA Module 3a vignette updates
- Review the new arg input for TADA_CreateParamRef(fillBy = "None", "Org" and "All)
- Review the new arg input for TADA_CreateUseParamRef(auto_assign = TRUE/FALSE)
- R documentation for these two functions and the examples
- The excel file export option and if there are any issues with the flagging columns, usability, dropdown lists, etc.

### CODE REVIEW

File: DESCRIPTION [hunk 1]
```diff
@@ -77,6 +77,7 @@ Imports:
     jsonlite, 
     openxlsx,
     rATTAINS,
```
Comment (cristinamullin) [inline DESCRIPTION]: Is rATTAINS still needed? It looks like it is only used to get the ATTAINS domain files now (in the files below), is that correct? 

TADA_GetATTAINSAUSiteCrosswalk
TADA_GetATTAINSParameterWQPCharRef
TADA_GetATTAINSOrgIDsRef
TADA_GetATTAINSParamUseOrgRef
TADA_TableExport (example only)
TADAModule3a.Rmd

File: R/ExampleData.R [hunk 2]
```diff
@@ -15,6 +15,20 @@
 #' @format A dataframe with 14592 rows and 152 variables
 NULL
 
+#' Data_Nutrients_UT_GetATTAINS
```
Comment (cristinamullin) [inline R/ExampleData.R]: I don't see this used anywhere. Is it used in a vignette?

Comment (wokenny13) [reply R/ExampleData.R]: This is used in the Rdocumentation example for one of the Mod 3 spatial functions I believe which is not reflected in this PR

File: R/ExampleData.R [hunk 3]
```diff
@@ -122,6 +136,20 @@ NULL
 #' @format A data frame with 84 rows and 161 variables
 NULL
 
+#' Data_WV_Mod1_Output_GetATTAINS
```
Comment (cristinamullin) [inline R/ExampleData.R]: same questions - I don't see this used anywhere. Is it used in a vignette?

File: DESCRIPTION (hunk 1 above)
Comment (wokenny13) [reply DESCRIPTION]: I believe we should be able to now leverage just rExpertQuery. The domain_value function within it should be working fine now. I can look to getting this incorporated to remove the rATTAINS dependency in those other functions.

Comment (cristinamullin) [reply DESCRIPTION]: Awesome! thank you - anytime we can remove dependencies that is really helpful

File: R/ExampleData.R (hunk 2 above)
Comment (cristinamullin) [reply R/ExampleData.R]: do you want to remove it from this PR and include it in the next one with the spatial functions?

File: DESCRIPTION (hunk 1 above)
Comment (hillarymarler) [reply DESCRIPTION]: I'm out the rest of this week @wokenny13, but if you want to work on replacing any rATTAINS use with rExpertQuery functions, I can help with that next week if that would be helpful.

File: R/ExampleData.R (hunk 2 above)
Comment (wokenny13) [reply R/ExampleData.R]: I can remove it from this PR

File: R/ExampleData.R (hunk 3 above)
Comment (wokenny13) [reply R/ExampleData.R]: I don't think this was being used anywhere (I will double check in the other branch with the mod 3 spatial functions), so I can also remove this as well in this PR for now. And if i do see it pop up anywhere it can be added back on.

File: inst/WORDLIST [hunk 4]
```diff
@@ -65,8 +68,13 @@ CountyCode
 CreateComparableID
 CreatePairRef
```
Comment (cristinamullin) [inline inst/WORDLIST]: CreatePairRef and CreateParamRef function names are too similar... let's update the names to better reflect what each function does

File: vignettes/images/FlowChartAUModule3.jpg
Comment (cristinamullin) [inline vignettes/images/FlowChartAUModule3.jpg:1]: Let's try to think of names that are more intuitive for users. This might be a good question for the subgroup.

TADA_ParametersForAnalysis
TADA_UsesForAnalysis
TADA_MonitoringLocationsForAnalysis

File: DESCRIPTION (hunk 1 above)
Comment (wokenny13) [reply DESCRIPTION]: I tried to make the update in TADA_GetATTAINSAUSiteCrosswalk consistent.

The number of rows do end up differing where au.crosswalk with 368 obs is from the orginal code with rATTAINS for AK

and the 208 obs is for the one with rExpertQuery::EQ_AUsMLs

Please take a look to review if the logic looks correct when you get the chance @hillarymarler I will push the updates through in this PR
image

File: R/ATTAINSCrosswalks.R [hunk 5]
```diff
@@ -565,7 +577,12 @@ TADA_UpdateMonitoringLocationsInATTAINS <- function(org_id = NULL,
 #' # Update the 'ATTAINS.FlagParameterName' values
 #' paramRef_UT3 <- TADA_CreateParamRef(Data_Nutrients_UT,
 #'   paramRef = paramRef_UT2,
-#'   org_id = "UTAHDWQ", excel = FALSE
+#'   org_id = "UTAHDWQ", fillBy = "None", excel = FALSE
+#' )
+#'
+#' # How does fillBy = "All" compare to paramRef_UT3?
+#' paramRef_UT4 <- TADA_CreateParamRef(Data_Nutrients_UT,
+#'   org_id = "UTAHDWQ", fillBy = "All", excel = FALSE
```
Comment (cristinamullin) [inline R/ATTAINSCrosswalks.R]: what do you think of calling this function input "autofill" instead of fillBy?

Comment (wokenny13) [reply R/ATTAINSCrosswalks.R]: In TADA_CreateUseParamRef we use the input name as "auto_assign". So not sure if we want to consider keeping these the same or not. I am open to considering different name for these functions and function inputs as were suggested in earlier comments too.

**Comment by wokenny13** [comment]
I updated the vignette to make the names of the crosswalk example data frames functionality more explicit and fixed some small flagging bugs so that everything should be working as intended.

I kept the function names and argument input the same for now and we can consider more appropriate new names. We can also consider the flagging columns in both functions and see if they can be reworded in any way for better clarity.

This should be in a good spot for a more final review now.

File: R/ATTAINSCrosswalks.R (hunk 5 above)
Comment (cristinamullin) [reply R/ATTAINSCrosswalks.R]: I agree they should be the same. I like autofill or auto_assign.

File: vignettes/images/FlowChartAUModule3.jpg
Comment (cristinamullin) [reply vignettes/images/FlowChartAUModule3.jpg:1]: other ideas:

TADA_SelectParameters
TADA_SelectUses
TADA_SelectMonitoringLocations

File: DESCRIPTION (hunk 1 above)
Comment (hillarymarler) [reply DESCRIPTION]: I will take a look at this today.

Comment (hillarymarler) [reply DESCRIPTION]: @wokenny13 the difference is that the rATTAINS version is returning all assessment units (active, retired, and historical), while the rExpertQuery version returns only active assessment units.

I think the desired behavior is to return only active assessment units, but we can modify the rExpertQuery version of the query to return retired/historical units too if that is desired. What are your thoughts?

Comment (wokenny13) [reply DESCRIPTION]: Only the active ones make sense to me. I thought rATTAINS was only returning the active ones as well, so this explains the difference.

File: vignettes/images/FlowChartAUModule3.jpg
Comment (cristinamullin) [inline vignettes/images/FlowChartAUModule3.jpg:1]: @wokenny13 can you remove the "CWA 303(d) assessments" language here. This should be more generic, for example, "Water Quality Data Analysis Process - WQP Monitoring Location Level" and "Water Quality Data Analysis Process - ATTAINS Assessment Unit Level"

**Comment by cristinamullin** [comment]
I changed fillBy to auto_assign in TADA_CreateParamRef for consistency. 

@wokenny13 I added one comment about the figures. Once that is addressed, this can be merged. Great work!!

File: vignettes/images/FlowChartAUModule3.jpg
Comment (wokenny13) [reply vignettes/images/FlowChartAUModule3.jpg:1]: This has been pushed through

**Review by cristinamullin — APPROVED** [review]
